name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    - name: Extract ngrok
      run: sudo tar -xvzf ngrok.tgz
    - name: Auth
      run: ./ngrok config add-authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: sudo sysctl -w net.ipv4.conf.all.route_localnet=1
    - run: sudo ufw allow 3389
    - run: sudo apt-get update && sudo apt-get install -y xrdp
    - name: Create Tunnel
      run: ./ngrok tcp 3389
